# Generated by Django 2.2 on 2019-05-10 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('definicion', '0006_auto_20190510_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_fin',
            new_name='fin',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_inicio',
            new_name='inicio',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('EP', 'En Produccion'), ('CO', 'Completado'), ('AP', 'Aprobado'), ('CA', 'Cancelado'), ('IN', 'Inactivo')], default='IN', max_length=2),
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definicion.Proyecto')),
                ('roles', models.ManyToManyField(to='auth.Group')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'miembros equipo',
                'default_permissions': (),
                'unique_together': {('usuario', 'proyecto')},
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='equipo',
            field=models.ManyToManyField(through='definicion.MiembroEquipo', to=settings.AUTH_USER_MODEL),
        ),
    ]
